# Generated by Django 4.1.3 on 2022-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='photo',
            field=models.ImageField(upload_to='static/pictures/'),
        ),
    ]
