# Generated by Django 4.1.3 on 2023-01-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='Описание',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
